# Generated by Django 5.2.8 on 2025-11-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='photo',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
